### ISSUE TITLE
If someone sends multiple messages in a row only announce their name for the first message

### ISSUE THREAD

**Issue by superusercode** [GnomedDev/Discord-TTS-Bot#111]
the "Hawking's" TTS bot worked like this and I preferred this behavior to someone's name being announced for every single message when they might be the only speaker using the tts bot. In a conversation i want it to say my name the first time but not if i sent multiple messages in a row.

**Comment by GnomedDev** [comment]
This is already implemented, if more than two people are in a vc (excluding bots). 
https://github.com/Discord-TTS/Bot/blob/master/tts_core/src/structs.rs#L226-L241

**Comment by GnomedDev** [comment]
Yes, a minute cooldown, I could avoid announcing for two people in a vc tbh.
