### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by silverfox0000** [GnomedDev/Discord-TTS-Bot#67]
Branch: `rust-rewrite`

Cargo Version: `1.57.0 (b2e52d7ca 2021-10-21)`
OS Type: Ubuntu 18.04 (bionic) [64-bit]

Compiler Log: [here](https://pastebin.com/raw/WjQKnBKh)

**Comment by GnomedDev** [comment]
Hey, that pastebin link is private so I cannot access it, although I only support the latest version of the rust compiler, currently I believe the MSRV is `1.58` as it uses the new format string syntax quite a lot.

**Comment by silverfox0000** [comment]
> Hey, that pastebin link is private so I cannot access it, although I only support the latest version of the rust compiler, currently I believe the MSRV is `1.58` as it uses the new format string syntax quite a lot.

Sorry my mistake i will set the password `G9Ftc0q8Gn`

**Comment by TheSuperGamer20578** [comment]
You need to use at least Rust 1.58.0. See:
https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings

**Comment by silverfox0000** [comment]
> You need to use at least Rust 1.58.0. See: https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings

Oh i just needed to update Rust. After update i will try now build
